example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist, show_xml, show_json, show_json_by_id, show_xml_by_id, register, login_user, logout_user, show_wishlist_ajax, wishlist_ajax_submit

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'), 
    path('logout/', logout_user, name='logout'),
    path('ajax/', show_wishlist_ajax, name='show_wishlist_ajax'),
    path('ajax/submit', wishlist_ajax_submit, name='wishlist_ajax_submit'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.

from django.db import models

class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from django.shortcuts import render
from wishlist.models import BarangWishlist
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.

@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Undissya Putri Maharani',
        'npm': '2106650935',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist.html", context)

@login_required(login_url='/wishlist/login/')
def show_wishlist_ajax(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Undissya Putri Maharani',
        'npm': '2106650935',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist_ajax.html", context)

@login_required(login_url='/wishlist/login/')
def wishlist_ajax_submit(request):
    if request.method == 'POST':
        newItem = BarangWishlist(
            nama_barang=request.POST.get('nama_barang'),
            harga_barang=request.POST.get('harga_barang'),
            deskripsi=request.POST.get('deskripsi'),
        )
        newItem.save()
    return HttpResponseRedirect(reverse('wishlist:show_wishlist_ajax'))

def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <body>
    <h1>Hello, world!</h1>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  </body>
</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

<nav class="navbar" style="background-color: #fd9ee1">
    <div class="container-fluid text-white">
      <a class="navbar-brand" href="#">Hi, {{nama}}!</a>
    </div>
  </nav>

  <nav class="navbar fixed-bottom navbar-light bg-dark text-white">
    <div class="container-fluid nav justify-content-center">
        <button type="button" class="btn btn-light"><a href="{% url 'wishlist:logout' %}">Logout</a></button>
    </div>
  </nav>

<div class="bg-white text-dark">
    <br>
        <h1 class="text-center">Your wishlist here!</h1>
    <br>
</div>

<div></div>
<table class="table table-hover">
    <thead>
        <tr>
            <th class="align-middle text-center">Nama Barang</th>
            <th class="align-middle text-center">Harga Barang</th>
            <th class="align-middle text-center">Deskripsi</th>
        </tr>
    </thead>
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
{% for barang in list_barang %}
    <tbody>
        <tr>
            <th class="align-middle text-center"><strong style="font-weight:normal; color: #323232">{{barang.nama_barang}}</strong></th>
            <th class="align-middle text-center"><strong style="font-weight:normal; color: #323232">{{barang.harga_barang}}</strong></th>
            <th class="align-middle text-center"><strong style="font-weight:normal; color: #323232">{{barang.deskripsi}}</strong></th>
        </tr>
    </tbody>
{% endfor %}
</table>
<br></br><br></br><br></br><br></br></br>
<h6 style="text-align: center">Sesi terakhir login: {{ last_login }}</h6>
<br><br><br>
</div>

{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block meta %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $(document).ready(function(){
        get_expr();
        $("added-data").submit(function(expr) {
            expr.prexprDefault();
            var url = expr.currentTarget.action;
            $.ajax({
                    url: url,
                    type: 'post',
                    dataType: 'json',
                    data: $("added-data").serialize(),
                    success: function(data) {
                        var tr = $("<tr></tr>");
                        for (const [key, temp] of Object.entries(data)) {
                            var x = $("<td></td>").html(temp);
                            tr.append(x);
                        }
                        $("#tabel-wishlist").append(tr);
                    },
                    error: function(){
                        alert("Wrong data!");
                    }
            });
        });
    });

    function get_expr() {
        $.get("../json", function(data) {
            data.forEach(element => {
                var tr = $("<tr></tr>");
                for (const [key, temp] of Object.entries(element.fields)) {
                    var x = $("<td></td>").html(temp);
                    tr.append(x);
                }
                $("#tabel-wishlist").append(tr);
            });
        });
    }
</script>
{% endblock meta %}
{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

<nav class="navbar" style="background-color: #fd9ee1">
    <div class="container-fluid text-white">
      <a class="navbar-brand" href="#">Hi, {{nama}}!</a>
    </div>
  </nav>

  <nav class="navbar fixed-bottom navbar-light bg-dark text-white">
    <div class="container-fluid nav justify-content-center">
        <button type="button" class="btn btn-light"><a href="{% url 'wishlist:logout' %}">Logout</a></button>
    </div>
  </nav>

<div class="bg-white text-dark">
    <br>
        <h1 class="text-center">Your wishlist here!</h1>
    <br>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $(document).ready(function(){
        get_expr();
        $("form#create-form").submit(function(expr) {
            expr.preventDefault();
            var url = expr.currentTarget.action;
            $.ajax({
                    url: url,
                    type: 'post',
                    dataType: 'json',
                    data: $("form#create-form").serialize(),
                    success: function(data) {
                        var tr = $("<tr></tr>");
                        for (const [key, temp] of Object.entries(data)) {
                            var x = $("<td></td>").html(temp);
                            tr.append(x);
                        }
                        $("#wishlist-table").append(tr);
                    },
                    error: function(){
                        alert("Wrong data!");
                    }
            });
        });
    });

    function get_expr() {
        $.get("../json", function(data) {
            data.forEach(element => {
                var tr = $("<tr></tr>");
                for (const [key, temp] of Object.entries(element.fields)) {
                    var x = $("<td></td>").html(temp);
                    tr.append(x);
                }
                $("#wishlist-table").append(tr);
            });
        });
    }
</script>

<table class="table table-hover" id="wishlist-table">
    <tr>
        <th class="align-middle text-center">Nama Barang</th>
        <th class="align-middle text-center">Harga Barang</th>
        <th class="align-middle text-center">Deskripsi</th>
    </tr>
</table>

<h5><center>Sesi terakhir login: {{ last_login }}</center></h5>

<div>
    <div>
        <form method="POST" action="./submit/" id="create-form" class="m-5">
            {% csrf_token %}
            <table>
                <tr>
                    <td>Nama Barang </td>
                    <td><input type="text" name="nama_barang" maxlength="100" placeholder="Nama Barang" class="form-control"></td>
                </tr>
                        
                <tr>
                    <td>Harga Barang </td>
                    <td><input type="number" name="harga_barang" placeholder="Harga Barang" class="form-control"></td>
                </tr>

                <tr>
                    <td>Deskripsi </td>
                    <td><input type="text" name="deskripsi" placeholder="Deskripsi" class="form-control"></td>
                </tr>
                <nav></nav>
                    <tr>
                        <td></td>
                        <td><input id="create-submit" class="btn btn-primary login_btn" type="submit" value="Submit"></td>
                    </tr>
                </nav>
            </table>
        </form>
    </div>
</div>

{% endblock content %}